/**
 * src/lib/printful-variants.ts
 * AUTO-GENERATED by scripts/fetch-printful-variant-ids.js
 * Generated: 2026-06-08T21:39:29.943Z
 *
 * Maps product slug → Printful sync_variant_id (and metadata).
 * The webhook uses this to auto-create Printful orders when PayPal payment completes.
 *
 * To regenerate after adding products:
 *   node scripts/fetch-printful-variant-ids.js
 */

export interface PrintfulVariant {
  variantId:   number;   // sync_variant_id — required for POST /orders
  name:        string;
  sku:         string;
  color:       string;
  size:        string;
  retailPrice: string;
  isEnabled:   boolean;
}

/** Map of product slug → available sync variants (ordered by Printful default) */
export const PRINTFUL_VARIANTS: Record<string, PrintfulVariant[]> = {
  "owl-cotton-kids-t-shirt": [
    {
      "variantId": 5342552474,
      "name": "OWL Cotton Kids T-Shirt / 3-4",
      "sku": "6A24ABB86A47F_12327",
      "color": "White",
      "size": "3-4",
      "retailPrice": "20.00"
    },
    {
      "variantId": 5342552475,
      "name": "OWL Cotton Kids T-Shirt / 5-6",
      "sku": "6A24ABB86A47F_12328",
      "color": "White",
      "size": "5-6",
      "retailPrice": "20.00"
    },
    {
      "variantId": 5342552476,
      "name": "OWL Cotton Kids T-Shirt / 7-8",
      "sku": "6A24ABB86A47F_12329",
      "color": "White",
      "size": "7-8",
      "retailPrice": "20.00"
    },
    {
      "variantId": 5342552477,
      "name": "OWL Cotton Kids T-Shirt / 9-11",
      "sku": "6A24ABB86A47F_12330",
      "color": "White",
      "size": "9-11",
      "retailPrice": "20.00"
    },
    {
      "variantId": 5342552478,
      "name": "OWL Cotton Kids T-Shirt / 12-13",
      "sku": "6A24ABB86A47F_12331",
      "color": "White",
      "size": "12-13",
      "retailPrice": "20.00"
    }
  ],
  "owl-throw-blanket": [
    {
      "variantId": 5342556835,
      "name": "OWL Throw Blanket / 60×80",
      "sku": "6A24AD1F0495E_13222",
      "color": null,
      "size": "60″×80″",
      "retailPrice": "51.00"
    },
    {
      "variantId": 5342556836,
      "name": "OWL Throw Blanket / 30×40",
      "sku": "6A24AD1F0495E_22609",
      "color": null,
      "size": "30″×40″",
      "retailPrice": "33.00"
    },
    {
      "variantId": 5342556837,
      "name": "OWL Throw Blanket / 50×60",
      "sku": "6A24AD1F0495E_10986",
      "color": null,
      "size": "50″×60″",
      "retailPrice": "34.50"
    }
  ],
  "owl-flat-bill-cap": [
    {
      "variantId": 5342550103,
      "name": "OWL Flat Bill Cap",
      "sku": "6A24AAC069DAD_4613",
      "color": "White",
      "size": "One size",
      "retailPrice": "19.00"
    }
  ],
  "owl-infant-bodysuit": [
    {
      "variantId": 5340404611,
      "name": "OWL Infant Bodysuit / 12M",
      "sku": "6A22D3D849E40_8172",
      "color": "White",
      "size": "12M",
      "retailPrice": "22.00"
    },
    {
      "variantId": 5340404612,
      "name": "OWL Infant Bodysuit / 18M",
      "sku": "6A22D3D849E40_8173",
      "color": "White",
      "size": "18M",
      "retailPrice": "22.00"
    },
    {
      "variantId": 5340404613,
      "name": "OWL Infant Bodysuit / 24M",
      "sku": "6A22D3D849E40_8174",
      "color": "White",
      "size": "24M",
      "retailPrice": "22.00"
    }
  ],
  "owl-sweatshirt": [
    {
      "variantId": 5340323864,
      "name": "OWL Sweatshirt / S",
      "sku": "6A22AF20CCBFB_12605",
      "color": "White",
      "size": "S",
      "retailPrice": "47.00"
    },
    {
      "variantId": 5340323868,
      "name": "OWL Sweatshirt / M",
      "sku": "6A22AF20CCBFB_12606",
      "color": "White",
      "size": "M",
      "retailPrice": "47.00"
    },
    {
      "variantId": 5340323872,
      "name": "OWL Sweatshirt / L",
      "sku": "6A22AF20CCBFB_12607",
      "color": "White",
      "size": "L",
      "retailPrice": "47.00"
    },
    {
      "variantId": 5340323876,
      "name": "OWL Sweatshirt / XL",
      "sku": "6A22AF20CCBFB_12608",
      "color": "White",
      "size": "XL",
      "retailPrice": "47.00"
    },
    {
      "variantId": 5340323880,
      "name": "OWL Sweatshirt / 2XL",
      "sku": "6A22AF20CCBFB_12609",
      "color": "White",
      "size": "2XL",
      "retailPrice": "49.00"
    }
  ],
  "owl-insulated-tumbler": [
    {
      "variantId": 5342538384,
      "name": "OWL Teal Insulated Tumbler With Straw",
      "sku": "6A24A7A59FDE5_19111",
      "color": "White",
      "size": "20 oz",
      "retailPrice": "26.50"
    }
  ],
  "owl-wine-tumbler": [
    {
      "variantId": 5342534291,
      "name": "OWL Teal Wine Tumbler",
      "sku": "6A24A68337554_16046",
      "color": "White",
      "size": "12 oz",
      "retailPrice": "23.50"
    }
  ],
  "owl-enamel-mug": [
    {
      "variantId": 5343605922,
      "name": "Enamel Mug",
      "sku": "6A2597CB81919_11189",
      "color": "White",
      "size": "12 oz",
      "retailPrice": "16.15"
    }
  ],
  "owl-glossy-mug": [
    {
      "variantId": 5340362726,
      "name": "White OWL Glossy Mug",
      "sku": "6A22C3403FDC8_1320",
      "color": "White",
      "size": "11 oz",
      "retailPrice": "18.00"
    }
  ],
  "owl-spiral-notebook": [
    {
      "variantId": 5342524899,
      "name": "OWL Spiral Notebook",
      "sku": "6A24A45861F95_12141",
      "color": "Dotted",
      "size": "5.5″×8.5″",
      "retailPrice": "17.50"
    }
  ],
  "owl-mouse-pad": [
    {
      "variantId": 5341958057,
      "name": "OWL Mouse Pad",
      "sku": "6A23F7185BD3C_13097",
      "color": "White",
      "size": "8.7\"x7.1\"",
      "retailPrice": "18.50"
    }
  ],
  "owl-water-bottle": [
    {
      "variantId": 5340625827,
      "name": "OWL Stainless Steel Water Bottle",
      "sku": "6A2312A0BE2FC_10798",
      "color": "White",
      "size": "17 oz",
      "retailPrice": "46.50"
    }
  ],
  "owl-duffle-bag": [
    {
      "variantId": 5340619293,
      "name": "OWL Space Planets Duffle Bag",
      "sku": "6A23105F3E13E_12021",
      "color": "White",
      "size": "One size",
      "retailPrice": "81.50"
    }
  ],
  "owl-backpack": [
    {
      "variantId": 5340550006,
      "name": "OWL Space Planet Backpack",
      "sku": "6A22FE4537F3E_9063",
      "color": "White",
      "size": "One size",
      "retailPrice": "67.00"
    }
  ],
  "owl-tote-bag": [
    {
      "variantId": 5340364668,
      "name": "OWL Eco-Friendly Tote Bag",
      "sku": "6A22C45573947_10458",
      "color": "Oyster",
      "size": "One size",
      "retailPrice": "35.50"
    }
  ],
  "owl-holographic-stickers": [
    {
      "variantId": 5341963135,
      "name": "OWL Holographic Stickers / 3x3",
      "sku": "6A23F983BB186_16705",
      "color": "Grey",
      "size": "3″×3″",
      "retailPrice": "6.50"
    },
    {
      "variantId": 5341963136,
      "name": "OWL Holographic Stickers / 4x4",
      "sku": "6A23F983BB186_16706",
      "color": "Grey",
      "size": "4″×4″",
      "retailPrice": "7.00"
    },
    {
      "variantId": 5341963137,
      "name": "OWL Holographic Stickers / 5.5x5.5",
      "sku": "6A23F983BB186_16707",
      "color": "Grey",
      "size": "5.5″×5.5″",
      "retailPrice": "7.50"
    }
  ],
  "owl-abcs-sticker-set": [
    {
      "variantId": 5342341752,
      "name": "OWL ABC's Sticker Set / 3x3",
      "sku": "6A246D8E34EB5_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342341753,
      "name": "OWL ABC's Sticker Set / 4x4",
      "sku": "6A246D8E34EB5_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342341754,
      "name": "OWL ABC's Sticker Set / 5.5x5.5",
      "sku": "6A246D8E34EB5_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-animal-sticker-set": [
    {
      "variantId": 5342377501,
      "name": "OWL Animal Sticker Set IV / 3x3",
      "sku": "6A24765025F08_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342377502,
      "name": "OWL Animal Sticker Set IV / 4x4",
      "sku": "6A24765025F08_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342377503,
      "name": "OWL Animal Sticker Set IV / 5.5x5.5",
      "sku": "6A24765025F08_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-animal-sticker-set-ii": [
    {
      "variantId": 5342373513,
      "name": "OWL Animal Sticker Set III / 3x3",
      "sku": "6A24757905F47_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342373514,
      "name": "OWL Animal Sticker Set III / 4x4",
      "sku": "6A24757905F47_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342373515,
      "name": "OWL Animal Sticker Set III / 5.5x5.5",
      "sku": "6A24757905F47_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-aplus-sticker-set": [
    {
      "variantId": 5342361695,
      "name": "OWL A+ Sticker Set / 3x3",
      "sku": "6A24732575D96_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342361696,
      "name": "OWL A+ Sticker Set / 4x4",
      "sku": "6A24732575D96_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342361697,
      "name": "OWL A+ Sticker Set / 5.5x5.5",
      "sku": "6A24732575D96_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-baby-boy-sticker-set": [
    {
      "variantId": 5342146977,
      "name": "OWL Baby Boy Sticker Set / 3x3",
      "sku": "6A243BB70C1BE_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342146978,
      "name": "OWL Baby Boy Sticker Set / 4x4",
      "sku": "6A243BB70C1BE_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342146979,
      "name": "OWL Baby Boy Sticker Set / 5.5x5.5",
      "sku": "6A243BB70C1BE_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-baby-girl-sticker-set": [
    {
      "variantId": 5342150062,
      "name": "OWL Baby Girl Sticker Set / 3x3",
      "sku": "6A243D08C0F06_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342150063,
      "name": "OWL Baby Girl Sticker Set / 4x4",
      "sku": "6A243D08C0F06_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342150064,
      "name": "OWL Baby Girl Sticker Set / 5.5x5.5",
      "sku": "6A243D08C0F06_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-colors-sticker-set": [
    {
      "variantId": 5342358556,
      "name": "OWL Colors Sticker Set / 3x3",
      "sku": "6A24726F11508_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342358557,
      "name": "OWL Colors Sticker Set / 4x4",
      "sku": "6A24726F11508_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342358558,
      "name": "OWL Colors Sticker Set / 5.5x5.5",
      "sku": "6A24726F11508_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-counting-sticker-set": [
    {
      "variantId": 5342365142,
      "name": "OWL Counting Sticker Set / 3x3",
      "sku": "6A2473E9320CE_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342365143,
      "name": "OWL Counting Sticker Set / 4x4",
      "sku": "6A2473E9320CE_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342365144,
      "name": "OWL Counting Sticker Set / 5.5x5.5",
      "sku": "6A2473E9320CE_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-holiday-sticker-set": [
    {
      "variantId": 5342345195,
      "name": "OWL Holiday Sticker Set / 3x3",
      "sku": "6A246EAD76F6E_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342345196,
      "name": "OWL Holiday Sticker Set / 4x4",
      "sku": "6A246EAD76F6E_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342345197,
      "name": "OWL Holiday Sticker Set / 5.5x5.5",
      "sku": "6A246EAD76F6E_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-insect-sticker-set": [
    {
      "variantId": 5342382295,
      "name": "OWL Insect Sticker Set II / 3x3",
      "sku": "6A2477C2C56CB_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342382296,
      "name": "OWL Insect Sticker Set II / 4x4",
      "sku": "6A2477C2C56CB_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342382298,
      "name": "OWL Insect Sticker Set II / 5.5x5.5",
      "sku": "6A2477C2C56CB_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-music-sticker-set": [
    {
      "variantId": 5342355663,
      "name": "OWL Music Sticker Set / 3x3",
      "sku": "6A2471AD802CD_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342355664,
      "name": "OWL Music Sticker Set / 4x4",
      "sku": "6A2471AD802CD_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342355665,
      "name": "OWL Music Sticker Set / 5.5x5.5",
      "sku": "6A2471AD802CD_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-numbers-sticker-set": [
    {
      "variantId": 5342161360,
      "name": "OWL Numbers Sticker Set / 3x3",
      "sku": "6A243FD918266_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342161361,
      "name": "OWL Numbers Sticker Set / 4x4",
      "sku": "6A243FD918266_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342161362,
      "name": "OWL Numbers Sticker Set / 5.5x5.5",
      "sku": "6A243FD918266_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-preschool-sticker-set": [
    {
      "variantId": 5342353466,
      "name": "OWL Pre-School Sticker Set / 3x3",
      "sku": "6A2471018E708_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342353467,
      "name": "OWL Pre-School Sticker Set / 4x4",
      "sku": "6A2471018E708_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342353468,
      "name": "OWL Pre-School Sticker Set / 5.5x5.5",
      "sku": "6A2471018E708_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ],
  "owl-seasons-sticker-set": [
    {
      "variantId": 5342349878,
      "name": "OWL Seasons Stickers Set / 3x3",
      "sku": "6A246FE7813F8_10163",
      "color": "White",
      "size": "3″×3″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342349879,
      "name": "OWL Seasons Stickers Set / 4x4",
      "sku": "6A246FE7813F8_10164",
      "color": "White",
      "size": "4″×4″",
      "retailPrice": "3.50"
    },
    {
      "variantId": 5342349880,
      "name": "OWL Seasons Stickers Set / 5.5x5.5",
      "sku": "6A246FE7813F8_10165",
      "color": "White",
      "size": "5.5″×5.5″",
      "retailPrice": "4.00"
    }
  ]
};

/**
 * Returns the best default variant for a product:
 * 1. First enabled variant
 * 2. First variant of any status
 * 3. null if product not found
 */
export function getDefaultVariant(slug: string): PrintfulVariant | null {
  const variants = PRINTFUL_VARIANTS[slug];
  if (!variants?.length) return null;
  return variants.find(v => v.isEnabled) ?? variants[0];
}

/**
 * Returns sync_variant_id for a product slug, or null if not found.
 * Used by the PayPal webhook to create Printful fulfillment orders.
 */
export function getPrintfulVariantId(slug: string): number | null {
  return getDefaultVariant(slug)?.variantId ?? null;
}
