import type { PrintableCardProps } from "@/components/marketing/printable-card";

export type SeedPrintable = PrintableCardProps & {
  ageBand: "0-1" | "1-2" | "2-3" | "3-4" | "4-5";
  description: string;
  learningOutcomes: string[];
  relatedVideoSlug?: string;
  relatedProductSlug?: string;
};

export const SEED_PRINTABLES: SeedPrintable[] = [
  // ── Educator workbooks — real PDFs (May 2026) ───────────────────────────
  {
    slug: "owl-wonders-colors-shapes",
    title: "OWL Wonders: Colors, Shapes & Sorting",
    ageRange: "2–5",
    ageBand: "2-3",
    pages: 12,
    freeOrPaid: "free",
    skill: "Alphabet",
    tone: "amber",
    previewSrc: "/printables/preview-01-01.png",
    downloadHref: "/printables/01-owl-wonders-colors-shapes-sorting.pdf",
    description: "Vibrant colors, shapes, and sorting activities to build early math foundations.",
    learningOutcomes: ["Color recognition", "Shape identification", "Sorting & classification", "Fine motor"],
    relatedVideoSlug: "learning-the-abcs",
  },
  {
    slug: "owl-explorers-numbers-patterns",
    title: "OWL Explorers: Numbers, Patterns & Thinking",
    ageRange: "2–6",
    ageBand: "2-3",
    pages: 14,
    freeOrPaid: "free",
    skill: "Numbers",
    tone: "teal",
    previewSrc: "/printables/preview-02-01.png",
    downloadHref: "/printables/02-owl-explorers-numbers-patterns-thinking.pdf",
    description: "Number recognition, patterns, and critical thinking challenges for curious young learners.",
    learningOutcomes: ["Number recognition 1–20", "Pattern completion", "Critical thinking", "Early math"],
    relatedProductSlug: "owl-counting-mat",
  },
  {
    slug: "owl-readers-letters-sounds",
    title: "OWL Readers: Letters, Sounds & Literacy",
    ageRange: "2–5",
    ageBand: "2-3",
    pages: 14,
    freeOrPaid: "free",
    skill: "SEL",
    tone: "rose",
    previewSrc: "/printables/preview-03-01.png",
    downloadHref: "/printables/03-owl-readers-letters-sounds-literacy.pdf",
    description: "Letter recognition, phonics, and early reading skills through multicultural OWL stories.",
    learningOutcomes: ["Letter recognition A–Z", "Phonics awareness", "Early literacy", "Tracing fine motor"],
    relatedProductSlug: "abc-flash-cards",
  },
  {
    slug: "owl-thinkers-math-foundations",
    title: "OWL Thinkers: Math Foundations",
    ageRange: "3–6",
    ageBand: "3-4",
    pages: 14,
    freeOrPaid: "free",
    skill: "K-readiness",
    tone: "forest",
    previewSrc: "/printables/preview-04-01.png",
    downloadHref: "/printables/04-owl-thinkers-math-foundations.pdf",
    description: "Core math foundations — counting, addition readiness, and number concepts for pre-K learners.",
    learningOutcomes: ["Counting to 20", "Addition readiness", "Number concepts", "Math vocabulary"],
    relatedProductSlug: "kreadiness-checklist",
  },
  // ── Legacy entries (kept for /printables route) ──────────────────────────
  {
    slug: "diwali-coloring",
    title: "Diwali coloring page",
    ageRange: "3–7",
    ageBand: "3-4",
    pages: 4,
    freeOrPaid: "free",
    skill: "Cultural",
    tone: "amber",
    description: "Four diya and rangoli scenes to color while talking about Diwali.",
    learningOutcomes: ["Diwali vocabulary", "Cultural respect", "Fine motor"],
    relatedVideoSlug: "lchaim-we-love-life",
  },
  {
    slug: "counting-mat-1-10",
    title: "Counting mat 1–10",
    ageRange: "2–4",
    ageBand: "2-3",
    pages: 1,
    freeOrPaid: "free",
    skill: "Numbers",
    tone: "teal",
    description: "Lay it on the kitchen table. Count, point, learn.",
    learningOutcomes: ["1:1 correspondence", "Counting to 10"],
    relatedVideoSlug: "letter-sound-song",
    relatedProductSlug: "owl-counting-mat",
  },
  {
    slug: "k-readiness-bundle",
    title: "K-readiness activity bundle",
    ageRange: "4–5",
    ageBand: "4-5",
    pages: 24,
    freeOrPaid: "paid",
    price: "$19.99",
    skill: "K-readiness",
    tone: "forest",
    description: "Twenty-four pages aligned to Common Core K and ELOF 60-month indicators.",
    learningOutcomes: ["Pre-reading", "Pre-writing", "Number sense"],
    relatedProductSlug: "kreadiness-checklist",
  },
  {
    slug: "homeschool-week-1",
    title: "Homeschool Week 1 (PreK 4)",
    ageRange: "4–5",
    ageBand: "4-5",
    pages: 12,
    freeOrPaid: "free",
    skill: "Homeschool",
    tone: "cream",
    description: "A complete homeschool week sample — five daily plans plus printables.",
    learningOutcomes: ["Daily structure", "K-readiness preview"],
  },
  {
    slug: "cultural-celebrations",
    title: "Cultural celebrations printable pack",
    ageRange: "3–7",
    ageBand: "3-4",
    pages: 16,
    freeOrPaid: "paid",
    price: "$14.99",
    skill: "Cultural",
    tone: "amber",
    description: "Twelve cultural celebration activities — one per month.",
    learningOutcomes: ["Cultural awareness", "Calendar literacy", "Vocabulary"],
  },
  {
    slug: "bilingual-flashcards",
    title: "Bilingual EN/ES flashcards",
    ageRange: "1–4",
    ageBand: "1-2",
    pages: 6,
    freeOrPaid: "free",
    skill: "Bilingual",
    tone: "teal",
    description: "Twenty-five common-word flashcards in English and Spanish.",
    learningOutcomes: ["Bilingual vocabulary", "Word-image association"],
    relatedProductSlug: "bilingual-word-cards",
  },
]

export const PRINTABLE_SKILL_OPTIONS = [
  { value: "Alphabet", label: "Alphabet" },
  { value: "Numbers", label: "Numbers" },
  { value: "SEL", label: "Feelings (SEL)" },
  { value: "Cultural", label: "Cultural" },
  { value: "Bilingual", label: "Bilingual" },
  { value: "K-readiness", label: "K-readiness" },
  { value: "Homeschool", label: "Homeschool" },
] as const;

export function findPrintableBySlug(slug: string) {
  return SEED_PRINTABLES.find((p) => p.slug === slug);
}
