import type { PrintableCardProps } from "@/components/marketing/printable-card";

export type SeedPrintable = PrintableCardProps & {
  ageBand: "0-1" | "1-2" | "2-3" | "3-4" | "4-5";
  description: string;
  learningOutcomes: string[];
  relatedVideoSlug?: string;
  relatedProductSlug?: string;
};

export const SEED_PRINTABLES: SeedPrintable[] = [
  // ── Educator workbooks — real PDFs (May 2026) ───────────────────────────
  {
    slug: "owl-wonders-colors-shapes",
    title: "OWL Wonders: Colors, Shapes & Sorting",
    ageRange: "2–5",
    ageBand: "2-3",
    pages: 12,
    freeOrPaid: "free",
    skill: "Alphabet",
    tone: "amber",
    previewSrc: "/printables/preview-01-01.png",
    downloadHref: "/printables/01-owl-wonders-colors-shapes-sorting.pdf",
    description: "Vibrant colors, shapes, and sorting activities to build early math foundations.",
    learningOutcomes: ["Color recognition", "Shape identification", "Sorting & classification", "Fine motor"],
    relatedVideoSlug: "learning-the-abcs",
  },
  {
    slug: "owl-explorers-numbers-patterns",
    title: "OWL Explorers: Numbers, Patterns & Thinking",
    ageRange: "2–6",
    ageBand: "2-3",
    pages: 14,
    freeOrPaid: "free",
    skill: "Numbers",
    tone: "teal",
    previewSrc: "/printables/preview-02-01.png",
    downloadHref: "/printables/02-owl-explorers-numbers-patterns-thinking.pdf",
    description: "Number recognition, patterns, and critical thinking challenges for curious young learners.",
    learningOutcomes: ["Number recognition 1–20", "Pattern completion", "Critical thinking", "Early math"],
    relatedProductSlug: "owl-counting-mat",
  },
  {
    slug: "owl-readers-letters-sounds",
    title: "OWL Readers: Letters, Sounds & Literacy",
    ageRange: "2–5",
    ageBand: "2-3",
    pages: 14,
    freeOrPaid: "free",
    skill: "SEL",
    tone: "rose",
    previewSrc: "/printables/preview-03-01.png",
    downloadHref: "/printables/03-owl-readers-letters-sounds-literacy.pdf",
    description: "Letter recognition, phonics, and early reading skills through multicultural OWL stories.",
    learningOutcomes: ["Letter recognition A–Z", "Phonics awareness", "Early literacy", "Tracing fine motor"],
    relatedProductSlug: "abc-flash-cards",
  },
  {
    slug: "owl-thinkers-math-foundations",
    title: "OWL Thinkers: Math Foundations",
    ageRange: "3–6",
    ageBand: "3-4",
    pages: 14,
    freeOrPaid: "free",
    skill: "K-readiness",
    tone: "forest",
    previewSrc: "/printables/preview-04-01.png",
    downloadHref: "/printables/04-owl-thinkers-math-foundations.pdf",
    description: "Core math foundations — counting, addition readiness, and number concepts for pre-K learners.",
    learningOutcomes: ["Counting to 20", "Addition readiness", "Number concepts", "Math vocabulary"],
    relatedProductSlug: "kreadiness-checklist",
  },
  // ── Legacy free cards ────────────────────────────────────────────────────
  {
    slug: "diwali-coloring",
    title: "Diwali coloring page",
    ageRange: "3–7",
    ageBand: "3-4",
    pages: 4,
    freeOrPaid: "free",
    skill: "Cultural",
    tone: "amber",
    previewSrc: "/images/printables/diwali-coloring.png",
    description: "Four diya and rangoli scenes to color while talking about Diwali.",
    learningOutcomes: ["Diwali vocabulary", "Cultural respect", "Fine motor"],
    relatedVideoSlug: "lchaim-we-love-life",
  },
  {
    slug: "counting-mat-1-10",
    title: "Counting mat 1–10",
    ageRange: "2–4",
    ageBand: "2-3",
    pages: 1,
    freeOrPaid: "free",
    skill: "Numbers",
    tone: "teal",
    previewSrc: "/images/printables/counting-mat.png",
    description: "Lay it on the kitchen table. Count, point, learn.",
    learningOutcomes: ["1:1 correspondence", "Counting to 10"],
    relatedVideoSlug: "letter-sound-song",
    relatedProductSlug: "owl-counting-mat",
  },
  {
    slug: "homeschool-week-1",
    title: "Homeschool Week 1 (PreK 4)",
    ageRange: "4–5",
    ageBand: "4-5",
    pages: 12,
    freeOrPaid: "free",
    skill: "Homeschool",
    tone: "cream",
    previewSrc: "/images/printables/homeschool-week-1.png",
    description: "A complete homeschool week sample — five daily plans plus printables.",
    learningOutcomes: ["Daily structure", "K-readiness preview"],
  },
  {
    slug: "bilingual-flashcards",
    title: "Bilingual EN/ES flashcards",
    ageRange: "1–4",
    ageBand: "1-2",
    pages: 6,
    freeOrPaid: "free",
    skill: "Bilingual",
    tone: "teal",
    previewSrc: "/images/printables/bilingual-flashcards.png",
    description: "Twenty-five common-word flashcards in English and Spanish.",
    learningOutcomes: ["Bilingual vocabulary", "Word-image association"],
    relatedProductSlug: "bilingual-word-cards",
  },
  // ── Bundle Packs ─────────────────────────────────────────────────────────
  {
    slug: "bundle-ages-2-3",
    title: "Ages 2–3 Early Learning Bundle",
    ageRange: "2–3",
    ageBand: "2-3",
    pages: 30,
    freeOrPaid: "paid",
    price: "$24.99",
    skill: "Early Learning",
    tone: "amber",
    previewSrc: "/images/bundles/bundle-ages-2-3.png",
    description: "A complete early learning bundle for toddlers — colors, shapes, letters, and sensory play activities.",
    learningOutcomes: ["Color & shape recognition", "Letter awareness", "Fine motor", "Sensory exploration"],
  },
  {
    slug: "bundle-ages-3-4",
    title: "Ages 3–4 Learning & Discovery Bundle",
    ageRange: "3–4",
    ageBand: "3-4",
    pages: 32,
    freeOrPaid: "paid",
    price: "$24.99",
    skill: "Discovery",
    tone: "teal",
    previewSrc: "/images/bundles/bundle-ages-3-4.png",
    description: "Hands-on learning and discovery activities that spark curiosity and build pre-K foundations.",
    learningOutcomes: ["Pre-reading skills", "Number sense", "Critical thinking", "Cultural awareness"],
  },
  {
    slug: "bundle-ages-4-5",
    title: "Ages 4–5 Curiosity & Skills Bundle",
    ageRange: "4–5",
    ageBand: "4-5",
    pages: 36,
    freeOrPaid: "paid",
    price: "$29.99",
    skill: "K-readiness",
    tone: "forest",
    previewSrc: "/images/bundles/bundle-ages-4-5.png",
    description: "Build curiosity and essential kindergarten-readiness skills through engaging multicultural activities.",
    learningOutcomes: ["Phonics readiness", "Math foundations", "Social-emotional skills", "K-readiness"],
  },
  {
    slug: "bundle-ages-5-6",
    title: "Ages 5–6 School Readiness & Confidence Bundle",
    ageRange: "5–6",
    ageBand: "4-5",
    pages: 40,
    freeOrPaid: "paid",
    price: "$29.99",
    skill: "K-readiness",
    tone: "rose",
    previewSrc: "/images/bundles/bundle-ages-5-6.png",
    description: "A comprehensive school-readiness bundle that builds confidence and prepares children for kindergarten success.",
    learningOutcomes: ["Reading readiness", "Math skills", "Writing foundations", "Confidence building"],
  },
]

export const PRINTABLE_SKILL_OPTIONS = [
  { value: "Alphabet", label: "Alphabet" },
  { value: "Numbers", label: "Numbers" },
  { value: "SEL", label: "Feelings (SEL)" },
  { value: "Cultural", label: "Cultural" },
  { value: "Bilingual", label: "Bilingual" },
  { value: "K-readiness", label: "K-readiness" },
  { value: "Homeschool", label: "Homeschool" },
  { value: "Early Learning", label: "Early Learning" },
  { value: "Discovery", label: "Discovery" },
] as const;

export function findPrintableBySlug(slug: string) {
  return SEED_PRINTABLES.find((p) => p.slug === slug);
}
