import type { ProductCardProps } from "@/components/marketing/product-card";

export type SeedProduct = ProductCardProps & {
  channel: "shopify" | "printify" | "printful" | "gumroad" | "etsy" | "kdp" | "tpt" | "website";
  productSource?: "printify" | "website_exclusive" | "digital_product";
  cost?: string;
  ageBand: "0-1" | "1-2" | "2-3" | "3-4" | "4-5" | "5-8";
  story: string;
  supportsLearningIn: string[];
  featured?: boolean;
  /**
   * **STORE STATE FLAG.** Every product in this seed is currently `isComingSoon: true`
   * because the Stripe/Shopify/Printify/Gumroad pipelines exist in scaffold form
   * only (see handoff.MD § "What's stubbed" — Phase 3 wakes them up).
   *
   * When a product goes live in commerce, flip this to `false`. The
   * <ProductCard> renders a corner ribbon and the detail page swaps the
   * Add-to-cart CTA for "Notify me when it drops" when this is true.
   *
   * Do NOT fabricate `isComingSoon: false` to make the design look livelier —
   * the truthful state IS that we are pre-launch on commerce. Ribbon-on-every-card
   * matches the redesign brief exactly: "All product cards in the store that are
   * not yet live must show a visible Coming Soon ribbon."
   */
  isComingSoon?: boolean;
};

export const SEED_PRODUCTS: SeedProduct[] = [
  // ── NEW (May 2026 spec): four featured products from the master prompt ──
  // The "Babies Complete Learning Bundle" has no commissioned image yet —
  // tonal placeholder is the honest skeleton. The other three have real
  // photos registered in src/lib/images.ts → products.
  {
    slug: "owl-babies-bundle",
    title: "OWL Babies Complete Learning Bundle",
    price: "$129",
    ageRange: "0–2",
    ageBand: "0-1",
    category: "Digital",
    tone: "amber",
    channel: "gumroad",
    story:
      "A starter bundle for a baby's first OWL year — plush companion, bilingual flash cards, movement activity pack, and Larissa's lullaby album. Built for sensory exploration, attachment routines, and slow-paced bedtime learning.",
    supportsLearningIn: [
      "Plush owl",
      "Bilingual flash cards",
      "Movement activity pack",
      "Lullaby album",
      "Sensory learning",
      "Educational bundle",
    ],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "larissa-plush",
    title: "Larissa Plush Set — 6 Ethnicities",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "amber",
    channel: "printify",
    story:
      "Six 10-inch Larissa plush companions — Black/African American, Latina, Asian, White, Middle Eastern, and Native American — each soft, huggable, and dressed in OWL's signature jacket. Removable outfits for pretend-play.",
    supportsLearningIn: [
      "Diverse representation",
      "Removable outfits",
      "Educational",
      "Safe for all ages",
    ],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "rhyme-time-game",
    title: "OWL Rhyme Time Card Game",
    price: "$12.99",
    ageRange: "4–5",
    ageBand: "4-5",
    category: "Flashcards",
    tone: "rose",
    channel: "printify",
    story:
      "48 thick rhyming cards with four ways to play (Go Fish · Rhyme Match · Memory Match · Rhyme Snap). Builds early literacy through rhyming patterns kids love.",
    supportsLearningIn: [
      "Literacy building",
      "Rhyming skills",
      "Memory games",
      "Ages 4–5",
    ],
    featured: true,
    isComingSoon: true,
  },
  // ── EXTRA: actual uploaded image was "Big Feelings Poster Set" ($18.99),
  //    not the bundle from the prompt. Adding both — bundle gets the slot,
  //    posters get the actual image so nothing is wasted.
  {
    slug: "big-feelings-posters",
    title: "OWL Big Feelings Poster Set",
    price: "$18.99",
    ageRange: "3–4",
    ageBand: "3-4",
    category: "Flashcards",
    tone: "teal",
    channel: "printify",
    story:
      "Three large 11×17 laminated SEL posters designed for PreK classrooms — How Am I Feeling, What To Do When I Feel, and Daily Mood Check-In. Multicultural face photography. Reinforces emotion vocabulary and self-regulation routines.",
    supportsLearningIn: [
      "Social-emotional learning",
      "Emotion vocabulary",
      "Daily check-in routine",
      "Classroom-ready",
    ],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "bilingual-word-cards",
    title: "OWL Toddler Word Cards",
    price: "$12.99",
    ageRange: "1–4",
    ageBand: "1-2",
    category: "Flashcards",
    tone: "amber",
    channel: "printify",
    story:
      "50 large 4×4 inch bilingual EN/ES flash cards organized into five categories (People · Food · Animals · Actions · Objects). Toddler-safe construction, easy to wipe.",
    supportsLearningIn: [
      "Bilingual learning",
      "Early vocabulary",
      "Categories",
      "Toddler safe",
    ],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "abc-flash-cards",
    title: "ABC flash cards",
    price: "$19.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Flashcards",
    tone: "teal",
    channel: "printify",
    story: "26 illustrated multicultural character cards. One letter, one face, one story.",
    supportsLearningIn: ["Letter recognition", "Letter-sound", "Vocabulary"],
    featured: true,
  isComingSoon: true,
  },
  {
    slug: "feelings-coloring",
    title: "Feelings coloring book",
    price: "$12.99",
    ageRange: "2–5",
    ageBand: "3-4",
    category: "Coloring",
    tone: "rose",
    channel: "kdp",
    story: "32 pages of feelings-named scenes children can color while talking through their day.",
    supportsLearningIn: ["Emotion vocabulary", "Fine motor", "SEL"],
    featured: true,
  isComingSoon: true,
  },
  {
    slug: "sticker-reward-chart",
    title: "Sticker reward chart",
    price: "$13.99",
    ageRange: "3–7",
    ageBand: "3-4",
    category: "Stickers",
    tone: "forest",
    channel: "printify",
    story: "OWL character stickers on a six-week chart. Build routines without shame-based rewards.",
    supportsLearningIn: ["Routine building", "Goal tracking", "Self-efficacy"],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "homeschool-starter",
    title: "Homeschool starter bundle",
    price: "$34.99",
    ageRange: "2–5",
    ageBand: "3-4",
    category: "Digital",
    tone: "cream",
    channel: "gumroad",
    story: "A digital starter pack with twelve printable activities, a parent guide, and access to four OWL videos.",
    supportsLearningIn: ["Early literacy", "Counting", "SEL", "Cultural awareness"],
  isComingSoon: true,
  },
  {
    slug: "lullaby-album",
    title: "Larissa's lullaby album",
    price: "$7.99",
    ageRange: "0–3",
    ageBand: "0-1",
    category: "Music",
    tone: "mist",
    channel: "gumroad",
    story: "Eleven original lullabies — recorded at 432 Hz for a calmer bedtime.",
    supportsLearningIn: ["Sleep routines", "Emotional regulation"],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "owl-counting-mat",
    title: "OWL counting mat 1–20",
    price: "$8.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Flashcards",
    tone: "amber",
    channel: "printify",
    story: "A laminated, wipe-clean mat with number 1–20 and one-to-one counting practice spaces.",
    supportsLearningIn: ["Counting", "Numeral recognition", "1:1 correspondence"],
  isComingSoon: true,
  },
  {
    slug: "emotion-tiles",
    title: "OWL emotion tiles",
    price: "$13.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Flashcards",
    tone: "rose",
    channel: "printify",
    story: "Twelve double-sided tiles with multicultural faces showing big feelings — perfect for circle time.",
    supportsLearningIn: ["Emotion vocabulary", "Empathy", "Storytelling"],
  isComingSoon: true,
  },
  {
    slug: "kreadiness-checklist",
    title: "K-readiness checklist",
    price: "$5.99",
    ageRange: "4–5",
    ageBand: "4-5",
    category: "Flashcards",
    tone: "teal",
    channel: "printify",
    story: "A 3-page laminated checklist tied to Common Core kindergarten standards and ELOF 60-month indicators.",
    supportsLearningIn: ["K-readiness", "Parent communication", "Standards alignment"],
  isComingSoon: true,
  },
  // ── Plush sets — May 2026 ────────────────────────────────────────────────
  {
    slug: "plush-bedtime-friends",
    title: "Larissa Plush Set — 6 Bedtime Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "mist",
    channel: "printify",
    story: "Six 10-inch bedtime owl companions — Dreamy Star, Sleepy Moon, Cloudy, Twinkle, Nighty Night, and Baby Owl. Perfect for calming bedtime routines and lullaby sing-alongs.",
    supportsLearningIn: ["Sleep routines", "Comfort objects", "Imaginative play", "Safe for all ages"],
    isComingSoon: true,
  },
  {
    slug: "plush-forest-friends",
    title: "Larissa Plush Set — 6 Forest Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "forest",
    channel: "printify",
    story: "Six nature-inspired owl plush companions — Fox, Bear, Deer, Raccoon, Hedgehog, and Forest Owl — each dressed in OWL's signature jacket. Inspired by the natural world.",
    supportsLearningIn: ["Nature vocabulary", "Animal recognition", "Imaginative play", "Educational"],
    isComingSoon: true,
  },
  {
    slug: "plush-ocean-friends",
    title: "Larissa Plush Set — 6 Ocean Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "teal",
    channel: "printify",
    story: "Six ocean-themed owl companions — Dolphin, Sea Turtle, Clownfish, Whale, Starfish, and Octopus. Bright colors and ocean-inspired fun for little explorers.",
    supportsLearningIn: ["Ocean vocabulary", "Marine life", "Imaginative play", "Educational"],
    isComingSoon: true,
  },
  {
    slug: "plush-safari-friends",
    title: "Larissa Plush Set — 6 Safari Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "amber",
    channel: "printify",
    story: "Six safari animal owl companions — Elephant, Giraffe, Lion, Zebra, Monkey, and Tiger. Wild about animals and educational fun.",
    supportsLearningIn: ["Animal vocabulary", "Safari animals", "Imaginative play", "Educational"],
    isComingSoon: true,
  },
  {
    slug: "plush-space-friends",
    title: "Larissa Plush Set — 6 Space Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "rose",
    channel: "printify",
    story: "Six out-of-this-world owl companions — Astronaut Owl, Alien Friend, Rocket Pilot, Planet Explorer, Comet Buddy, and Galaxy Girl. For little dreamers who reach for the stars.",
    supportsLearningIn: ["Space vocabulary", "STEM curiosity", "Imaginative play", "Educational"],
    isComingSoon: true,
  },
  // ── Music albums — May 2026 ──────────────────────────────────────────────
  {
    slug: "counting-math-album",
    title: "Larissa's Counting & Math Party!",
    price: "$9.99",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Music",
    tone: "amber",
    channel: "gumroad",
    story: "Fun songs about numbers, shapes, patterns, and more — recorded at a toddler-friendly tempo with call-and-response phrasing.",
    supportsLearningIn: ["Counting", "Number recognition", "Shapes", "Patterns"],
    isComingSoon: true,
  },
  {
    slug: "abc-adventure-album",
    title: "Larissa's ABC Adventure Songs",
    price: "$9.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Music",
    tone: "teal",
    channel: "gumroad",
    story: "Catchy songs to learn letters, phonics, and spelling — each track focuses on a letter cluster with memorable melodies.",
    supportsLearningIn: ["Letter recognition", "Phonics", "Spelling", "Early literacy"],
    isComingSoon: true,
  },
  {
    slug: "around-world-album",
    title: "Larissa's Around the World",
    price: "$9.99",
    ageRange: "2–8",
    ageBand: "2-3",
    category: "Music",
    tone: "rose",
    channel: "gumroad",
    story: "Songs about cultures we love — explore, learn, and sing together. Multicultural musical celebration for the whole family.",
    supportsLearningIn: ["Cultural awareness", "World music", "Multicultural vocabulary", "Global citizenship"],
    isComingSoon: true,
  },
  {
    slug: "calm-down-album",
    title: "Larissa's Calm Down & Mindfulness Songs",
    price: "$9.99",
    ageRange: "2–8",
    ageBand: "2-3",
    category: "Music",
    tone: "mist",
    channel: "gumroad",
    story: "Gentle songs to help little hearts and minds feel calm and happy. Breathe. Relax. Be Kind.",
    supportsLearningIn: ["Mindfulness", "Emotional regulation", "Breathing exercises", "SEL"],
    isComingSoon: true,
  },
  // ── Coloring books — May 2026 ────────────────────────────────────────────
  {
    slug: "numbers-math-coloring",
    title: "OWL Numbers & Math Magic Coloring Book",
    price: "$7.99",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Coloring",
    tone: "amber",
    channel: "kdp",
    story: "Count and color your way through numbers 1–20 with OWL. Each page pairs a numeral with matching objects to count and color.",
    supportsLearningIn: ["Counting", "Number recognition", "Fine motor", "Math concepts"],
    isComingSoon: true,
  },
  {
    slug: "abc-coloring-book",
    title: "OWL ABC Coloring Book",
    price: "$7.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Coloring",
    tone: "teal",
    channel: "kdp",
    story: "A is for Owl — 26 letter pages with OWL characters to color while learning the alphabet.",
    supportsLearningIn: ["Letter recognition", "Fine motor", "Early literacy", "Creative expression"],
    isComingSoon: true,
  },
  {
    slug: "abcs-world-coloring",
    title: "OWL ABCs Around the World Coloring Book",
    price: "$8.99",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Coloring",
    tone: "rose",
    channel: "kdp",
    story: "A Multicultural Alphabet Coloring Book — each letter features a child from a different culture with their traditional dress and a meaningful word.",
    supportsLearningIn: ["Letter recognition", "Multicultural awareness", "Fine motor", "Global vocabulary"],
    isComingSoon: true,
  },
  // ── Sticker sets — May 2026 ──────────────────────────────────────────────
  {
    slug: "owl-emotions-stickers",
    title: "OWL Emotions Sticker Set",
    price: "$5.99",
    ageRange: "2–7",
    ageBand: "2-3",
    category: "Stickers",
    tone: "rose",
    channel: "printify",
    story: "12 owl emotion face stickers — Happy, Sad, Angry, Calm, Excited, Worried, Scared, Sleepy, Surprised, Silly, Loved, and Proud. Perfect for feelings check-ins.",
    supportsLearningIn: ["Emotion vocabulary", "SEL", "Feelings identification", "Self-awareness"],
    isComingSoon: true,
  },
  {
    slug: "owl-cultural-stickers",
    title: "OWL Cultural Celebrations Sticker Bundle",
    price: "$6.99",
    ageRange: "3–8",
    ageBand: "3-4",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    story: "12 multicultural holiday owl stickers — Diwali, Kwanzaa, Hanukkah, Lunar New Year, Eid, Holi, Juneteenth, Día de Muertos, Carnival, Nowruz, Christmas, and Thanksgiving.",
    supportsLearningIn: ["Cultural awareness", "Holiday vocabulary", "Multicultural education", "Global citizenship"],
    isComingSoon: true,
  },
  {
    slug: "owl-baby-girl-stickers",
    title: "Baby Girl OWL Sticker Sheet",
    price: "$4.99",
    ageRange: "0–2",
    ageBand: "0-1",
    category: "Stickers",
    tone: "rose",
    channel: "printify",
    story: "12 pastel baby owl stickers — Bow, Heart, Daisy, Cozy, Rattle, Binky, Bottle, Dream, Star, Flutter, Princess, and Sweet Hoot. A sweet gift for little ones.",
    supportsLearningIn: ["Reward system", "Fine motor", "Imaginative play", "Gift giving"],
    isComingSoon: true,
  },
  {
    slug: "owl-big-kid-boy-stickers",
    title: "Big Kid Boy OWL Sticker Sheet",
    price: "$4.99",
    ageRange: "3–5",
    ageBand: "3-4",
    category: "Stickers",
    tone: "teal",
    channel: "printify",
    story: "12 adventure owl stickers for big kids — School, Soccer, Read, Write, Star, Strong, Dream Big, Cool, Create, High Five, Champ, and I Am Brave.",
    supportsLearningIn: ["Growth mindset", "Reward system", "Self-confidence", "Achievement recognition"],
    isComingSoon: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRINTIFY / PRINTFUL PRODUCTS — imported June 2026
  // Source: OWL_Product_Pricing.xlsx (Printful Dashboard)
  // All assigned productSource: "printify", isComingSoon: true at launch.
  // Flip isComingSoon: false when a product goes live in Printify.
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Apparel ───────────────────────────────────────────────────────────────
  {
    slug: "owl-t-shirt",
    title: "OWL T-Shirt",
    price: "$30.50",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Apparel",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$18.50",
    story: "The official OWL Sing Together tee — soft, vibrant, and built for everyday wear. Features Larissa's signature OWL branding in full color.",
    supportsLearningIn: ["Brand pride", "Multicultural identity", "Community"],
    isComingSoon: true,
  },
  {
    slug: "owl-cotton-kids-t-shirt",
    title: "OWL Cotton Kids T-Shirt",
    price: "$20.00",
    ageRange: "Kids",
    ageBand: "3-4",
    category: "Apparel",
    tone: "rose",
    channel: "printify",
    productSource: "printify",
    cost: "$15.25",
    story: "A soft 100% cotton tee made for little OWL fans. Durable, washable, and perfect for school, play, or sing-along sessions.",
    supportsLearningIn: ["Brand expression", "Multicultural identity"],
    isComingSoon: true,
  },
  {
    slug: "owl-infant-bodysuit",
    title: "OWL Infant Bodysuit",
    price: "$22.00",
    ageRange: "Infant",
    ageBand: "0-1",
    category: "Apparel",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$11.75",
    story: "An adorable OWL-branded bodysuit for the littlest learners. Soft, snug, and made for OWL babies everywhere.",
    supportsLearningIn: ["Brand pride", "Gift giving", "Infant comfort"],
    isComingSoon: true,
  },
  {
    slug: "owl-sweatshirt",
    title: "OWL Sweatshirt",
    price: "$48.00",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Apparel",
    tone: "forest",
    channel: "printify",
    productSource: "printify",
    cost: "$36.75",
    story: "A premium OWL Sing Together crewneck sweatshirt — cozy, warm, and perfect for parents, educators, and OWL supporters.",
    supportsLearningIn: ["Brand pride", "Community", "Educator identity"],
    isComingSoon: true,
  },

  // ── Headwear ──────────────────────────────────────────────────────────────
  {
    slug: "owl-flat-bill-cap",
    title: "OWL Flat Bill Cap",
    price: "$19.00",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Headwear",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$14.50",
    story: "The OWL Flat Bill Cap — a clean, structured cap with the OWL logo embroidered front and center. Snap-back fit for all sizes.",
    supportsLearningIn: ["Brand pride", "Educator identity"],
    isComingSoon: true,
  },
  {
    slug: "owl-embroidered-beanie",
    title: "Embroidered OWL Beanie",
    price: "$23.50",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Headwear",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$17.90",
    story: "A cozy OWL Sing Together embroidered beanie — perfect for cold mornings, school runs, or singing outdoors.",
    supportsLearningIn: ["Brand pride", "Community", "Gift giving"],
    isComingSoon: true,
  },

  // ── Drinkware ─────────────────────────────────────────────────────────────
  {
    slug: "owl-insulated-tumbler",
    title: "OWL Teal Insulated Tumbler W/ Straw",
    price: "$26.50",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Drinkware",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$20.35",
    story: "Stay hydrated while you sing along! The OWL insulated tumbler keeps drinks cold for 24 hours and hot for 12 — with a reusable straw included.",
    supportsLearningIn: ["Healthy habits", "Brand pride"],
    isComingSoon: true,
  },
  {
    slug: "owl-wine-tumbler",
    title: "OWL Teal Wine Tumbler",
    price: "$23.50",
    ageRange: "Adults",
    ageBand: "5-8",
    category: "Drinkware",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$17.52",
    story: "The OWL teal wine tumbler — a thoughtful gift for the OWL-loving parent or educator in your life. Double-walled and BPA-free.",
    supportsLearningIn: ["Brand pride", "Gift giving", "Educator appreciation"],
    isComingSoon: true,
  },
  {
    slug: "owl-enamel-mug",
    title: "OWL Teal Enamel Mug",
    price: "$16.50",
    ageRange: "Adults",
    ageBand: "5-8",
    category: "Drinkware",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$12.50",
    story: "The OWL enamel mug — a classroom and coffee table staple. Durable, dishwasher-safe, and full of OWL warmth.",
    supportsLearningIn: ["Brand pride", "Educator appreciation", "Gift giving"],
    isComingSoon: true,
  },
  {
    slug: "owl-glossy-mug",
    title: "White OWL Glossy Mug",
    price: "$18.00",
    ageRange: "Adults",
    ageBand: "5-8",
    category: "Drinkware",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$6.50",
    story: "A classic white 11oz ceramic mug with the full OWL Sing Together design. Perfect for morning tea, coffee, or hot cocoa while reading.",
    supportsLearningIn: ["Brand pride", "Gift giving"],
    isComingSoon: true,
  },

  // ── Home & Accessories ────────────────────────────────────────────────────
  {
    slug: "owl-throw-blanket",
    title: "OWL Throw Blanket",
    price: "$42.00",
    ageRange: "All ages",
    ageBand: "0-1",
    category: "Home & Accessories",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$32.12",
    story: "Cozy up with the OWL Throw Blanket — soft, warm, and printed with Larissa's signature OWL design. Perfect for storytime, naptime, and family movie nights.",
    supportsLearningIn: ["Comfort object", "Sensory experience", "Bedtime routines"],
    isComingSoon: true,
  },
  {
    slug: "owl-spiral-notebook",
    title: "OWL Spiral Notebook",
    price: "$17.50",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Home & Accessories",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$13.25",
    story: "The OWL Spiral Notebook — ideal for lesson planning, journaling, or classroom notes. 120 lined pages with the full OWL Sing Together cover design.",
    supportsLearningIn: ["Writing skills", "Educator tools", "Organization"],
    isComingSoon: true,
  },
  {
    slug: "owl-mouse-pad",
    title: "OWL Mouse Pad",
    price: "$18.50",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Home & Accessories",
    tone: "forest",
    channel: "printify",
    productSource: "printify",
    cost: "$9.50",
    story: "An OWL-branded mouse pad for your home office or classroom desk. Non-slip base, vibrant print, and the perfect everyday reminder of why you do this work.",
    supportsLearningIn: ["Educator workspace", "Brand pride"],
    isComingSoon: true,
  },
  {
    slug: "owl-water-bottle",
    title: "OWL Stainless Steel Water Bottle",
    price: "$46.50",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Home & Accessories",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$21.93",
    story: "A premium 20oz stainless steel water bottle — double-walled, leak-proof, and printed with OWL's signature design. Built for busy parents and on-the-go educators.",
    supportsLearningIn: ["Healthy habits", "Eco-friendly living", "Brand pride"],
    isComingSoon: true,
  },
  {
    slug: "owl-duffle-bag",
    title: "OWL Space Planets Duffle Bag",
    price: "$81.50",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Home & Accessories",
    tone: "mist",
    channel: "printify",
    productSource: "printify",
    cost: "$69.50",
    story: "The OWL Space Planets Duffle Bag — a spacious, durable bag for classroom materials, weekend adventures, or school trips. Fully printed with OWL's space-themed design.",
    supportsLearningIn: ["Organization", "STEM curiosity", "Travel"],
    isComingSoon: true,
  },
  {
    slug: "owl-backpack",
    title: "OWL Space Planet Backpack",
    price: "$67.00",
    ageRange: "All ages",
    ageBand: "3-4",
    category: "Home & Accessories",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$38.50",
    story: "The OWL Space Planet Backpack — roomy, padded, and covered in OWL's signature space design. Perfect for school, day trips, and classroom adventures.",
    supportsLearningIn: ["Organization", "STEM curiosity", "School readiness"],
    isComingSoon: true,
  },
  {
    slug: "owl-tote-bag",
    title: "OWL Eco-Friendly Tote Bag",
    price: "$35.50",
    ageRange: "All ages",
    ageBand: "5-8",
    category: "Home & Accessories",
    tone: "forest",
    channel: "printify",
    productSource: "printify",
    cost: "$21.45",
    story: "The OWL Eco-Friendly Tote Bag — reusable, sturdy, and sustainably made. Perfect for groceries, library runs, or classroom materials.",
    supportsLearningIn: ["Eco-friendly habits", "Organization", "Brand pride"],
    isComingSoon: true,
  },

  // ── Sticker Sets ──────────────────────────────────────────────────────────
  {
    slug: "owl-holographic-stickers",
    title: "OWL Holographic Stickers",
    price: "$7.00",
    ageRange: "3–8",
    ageBand: "3-4",
    category: "Stickers",
    tone: "rose",
    channel: "printify",
    productSource: "printify",
    cost: "$5.13",
    story: "Shiny, eye-catching holographic OWL stickers that shimmer and shine. Perfect for reward charts, water bottles, notebooks, and more.",
    supportsLearningIn: ["Reward systems", "Motivation", "Creative expression"],
    isComingSoon: true,
  },
  {
    slug: "owl-insect-sticker-set",
    title: "OWL Insect Sticker Set",
    price: "$3.75",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Stickers",
    tone: "forest",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Explore the world of insects with OWL! This sticker set features colorful, illustrated bugs for science learning and creative play.",
    supportsLearningIn: ["Nature science", "Insect vocabulary", "STEM curiosity"],
    isComingSoon: true,
  },
  {
    slug: "owl-insect-sticker-set-ii",
    title: "OWL Insect Sticker Set II",
    price: "$3.75",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Stickers",
    tone: "forest",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "More insects to discover! OWL Insect Set II adds a fresh collection of illustrated bugs and critters for curious little scientists.",
    supportsLearningIn: ["Nature science", "Insect vocabulary", "STEM curiosity"],
    isComingSoon: true,
  },
  {
    slug: "owl-animal-sticker-set",
    title: "OWL Animal Sticker Set",
    price: "$3.75",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Meet OWL's animal friends! This sticker set features illustrated animals from around the world for vocabulary building and imaginative play.",
    supportsLearningIn: ["Animal vocabulary", "Nature science", "Creative play"],
    isComingSoon: true,
  },
  {
    slug: "owl-animal-sticker-set-ii",
    title: "OWL Animal Sticker Set II",
    price: "$3.75",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "More animal adventures! OWL Animal Set II brings a second wave of illustrated creatures for learning and play.",
    supportsLearningIn: ["Animal vocabulary", "Nature science", "Creative play"],
    isComingSoon: true,
  },
  {
    slug: "owl-animal-sticker-set-iii",
    title: "OWL Animal Sticker Set III",
    price: "$3.75",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "The animal collection continues! OWL Animal Set III features even more diverse illustrated animals for storytelling and science.",
    supportsLearningIn: ["Animal vocabulary", "Biodiversity", "Creative play"],
    isComingSoon: true,
  },
  {
    slug: "owl-animal-sticker-set-iv",
    title: "OWL Animal Sticker Set IV",
    price: "$3.75",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Four sets in — OWL Animal Set IV completes the ultimate animal sticker collection for little nature lovers.",
    supportsLearningIn: ["Animal vocabulary", "Biodiversity", "Collector's series"],
    isComingSoon: true,
  },
  {
    slug: "owl-counting-sticker-set",
    title: "OWL Counting Sticker Set",
    price: "$3.75",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Stickers",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Count along with OWL! Illustrated number stickers for 1–10 that make math practice fun and visual.",
    supportsLearningIn: ["Counting", "Number recognition", "Math readiness"],
    isComingSoon: true,
  },
  {
    slug: "owl-aplus-sticker-set",
    title: "OWL A+ Sticker Set",
    price: "$3.75",
    ageRange: "3–8",
    ageBand: "3-4",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Celebrate achievement with the OWL A+ Sticker Set. Perfect for teachers rewarding great work and parents tracking milestones.",
    supportsLearningIn: ["Achievement recognition", "Growth mindset", "Reward systems"],
    isComingSoon: true,
  },
  {
    slug: "owl-colors-sticker-set",
    title: "OWL Colors Sticker Set",
    price: "$3.75",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Stickers",
    tone: "rose",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Learn colors with OWL! Vibrant illustrated stickers in every color of the rainbow, ideal for early color recognition activities.",
    supportsLearningIn: ["Color recognition", "Early vocabulary", "Creative play"],
    isComingSoon: true,
  },
  {
    slug: "owl-music-sticker-set",
    title: "OWL Music Sticker Set",
    price: "$3.75",
    ageRange: "2–8",
    ageBand: "2-3",
    category: "Stickers",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Music-themed OWL stickers featuring instruments, notes, and musical characters. Perfect for music class rewards or instrument notebooks.",
    supportsLearningIn: ["Music vocabulary", "Instrument recognition", "Arts appreciation"],
    isComingSoon: true,
  },
  {
    slug: "owl-preschool-sticker-set",
    title: "OWL Pre-School Sticker Set",
    price: "$3.75",
    ageRange: "3–5",
    ageBand: "3-4",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Everything preschool in one sticker set! Letters, numbers, shapes, colors, and classroom scenes for PreK learners.",
    supportsLearningIn: ["Preschool readiness", "Early literacy", "Math concepts"],
    isComingSoon: true,
  },
  {
    slug: "owl-seasons-sticker-set",
    title: "OWL Seasons Sticker Set",
    price: "$3.75",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Stickers",
    tone: "forest",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Explore all four seasons with OWL! Illustrated stickers for spring, summer, fall, and winter — perfect for seasonal learning units.",
    supportsLearningIn: ["Seasonal vocabulary", "Nature science", "Calendar awareness"],
    isComingSoon: true,
  },
  {
    slug: "owl-holiday-sticker-set",
    title: "OWL Holiday Sticker Set",
    price: "$3.75",
    ageRange: "3–8",
    ageBand: "3-4",
    category: "Stickers",
    tone: "rose",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Celebrate multicultural holidays with OWL! Illustrated stickers for holidays from around the world — Diwali, Kwanzaa, Hanukkah, Lunar New Year, and more.",
    supportsLearningIn: ["Cultural awareness", "Holiday vocabulary", "Multicultural education"],
    isComingSoon: true,
  },
  {
    slug: "owl-abcs-sticker-set",
    title: "OWL ABC's Sticker Set",
    price: "$3.75",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Stickers",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Alphabet stickers for little learners! OWL's ABC sticker set features illustrated letters A–Z with kid-friendly images for each letter.",
    supportsLearningIn: ["Letter recognition", "Phonics", "Early literacy"],
    isComingSoon: true,
  },
  {
    slug: "owl-numbers-sticker-set",
    title: "OWL Numbers Sticker Set",
    price: "$3.75",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Number stickers for math readiness! OWL Numbers Set covers 0–20 with illustrated numerals and counting objects.",
    supportsLearningIn: ["Number recognition", "Counting", "Math readiness"],
    isComingSoon: true,
  },
  {
    slug: "owl-baby-boy-sticker-set",
    title: "OWL Baby Boy Sticker Set",
    price: "$3.75",
    ageRange: "0–3",
    ageBand: "0-1",
    category: "Stickers",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Sweet baby boy OWL stickers — perfect for milestone cards, scrapbooks, and celebrating a new little learner.",
    supportsLearningIn: ["Milestone tracking", "Gift giving", "Creative expression"],
    isComingSoon: true,
  },
  {
    slug: "owl-baby-girl-sticker-set",
    title: "OWL Baby Girl Sticker Set",
    price: "$3.75",
    ageRange: "0–3",
    ageBand: "0-1",
    category: "Stickers",
    tone: "rose",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Sweet baby girl OWL stickers — perfect for milestone cards, scrapbooks, and celebrating a new little learner.",
    supportsLearningIn: ["Milestone tracking", "Gift giving", "Creative expression"],
    isComingSoon: true,
  },

  // ── Extra sticker sets (images found in Printify folder, not in spreadsheet) ──
  {
    slug: "owl-explorer-sticker-set",
    title: "OWL Explorer Sticker Set",
    price: "$3.75",
    ageRange: "3–7",
    ageBand: "3-4",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Adventure awaits! The OWL Explorer sticker set features illustrated adventurers, maps, compasses, and discovery tools for curious young explorers.",
    supportsLearningIn: ["Geography", "Curiosity", "STEM exploration", "Adventure mindset"],
    isComingSoon: true,
  },
  {
    slug: "owl-science-sticker-set",
    title: "OWL Science Sticker Set",
    price: "$3.75",
    ageRange: "3–8",
    ageBand: "3-4",
    category: "Stickers",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Science is for everyone! OWL Science stickers feature lab equipment, atoms, plants, and STEM characters to spark scientific thinking.",
    supportsLearningIn: ["STEM curiosity", "Science vocabulary", "Scientific method", "Inquiry learning"],
    isComingSoon: true,
  },
  {
    slug: "owl-swimming-sticker-set",
    title: "OWL Swimming Sticker Set",
    price: "$3.75",
    ageRange: "2–7",
    ageBand: "2-3",
    category: "Stickers",
    tone: "teal",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Splash into learning! The OWL Swimming sticker set features aquatic animals, swim gear, and water-themed designs for little swimmers.",
    supportsLearningIn: ["Water safety awareness", "Marine vocabulary", "Physical activity", "Ocean science"],
    isComingSoon: true,
  },
  {
    slug: "owl-math-sticker-set",
    title: "OWL Math Sticker Set",
    price: "$3.75",
    ageRange: "3–7",
    ageBand: "3-4",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    productSource: "printify",
    cost: "$2.63",
    story: "Make math exciting! OWL Math stickers feature numbers, equations, shapes, and math symbols that make learning feel like play.",
    supportsLearningIn: ["Math vocabulary", "Number concepts", "Shapes and patterns", "K-readiness"],
    isComingSoon: true,
  },
];

export const PRODUCT_CATEGORY_OPTIONS = [
  { value: "Apparel",            label: "Apparel" },
  { value: "Headwear",           label: "Headwear" },
  { value: "Drinkware",          label: "Drinkware" },
  { value: "Home & Accessories", label: "Home & Accessories" },
  { value: "Stickers",           label: "Stickers" },
  { value: "Plush",              label: "Plush" },
  { value: "Flashcards",         label: "Flashcards" },
  { value: "Coloring",           label: "Coloring" },
  { value: "Digital",            label: "Digital" },
  { value: "Music",              label: "Music" },
  { value: "Backpacks",          label: "Backpacks" },
  { value: "Bundles",            label: "Bundles" },
] as const;

export function findProductBySlug(slug: string) {
  return SEED_PRODUCTS.find((p) => p.slug === slug);
}
