import type { ProductCardProps } from "@/components/marketing/product-card";

export type SeedProduct = ProductCardProps & {
  channel: "shopify" | "printify" | "gumroad" | "etsy" | "kdp" | "tpt";
  ageBand: "0-1" | "1-2" | "2-3" | "3-4" | "4-5" | "5-8";
  story: string;
  supportsLearningIn: string[];
  featured?: boolean;
  /**
   * **STORE STATE FLAG.** Every product in this seed is currently `isComingSoon: true`
   * because the Stripe/Shopify/Printify/Gumroad pipelines exist in scaffold form
   * only (see handoff.MD § "What's stubbed" — Phase 3 wakes them up).
   *
   * When a product goes live in commerce, flip this to `false`. The
   * <ProductCard> renders a corner ribbon and the detail page swaps the
   * Add-to-cart CTA for "Notify me when it drops" when this is true.
   *
   * Do NOT fabricate `isComingSoon: false` to make the design look livelier —
   * the truthful state IS that we are pre-launch on commerce. Ribbon-on-every-card
   * matches the redesign brief exactly: "All product cards in the store that are
   * not yet live must show a visible Coming Soon ribbon."
   */
  isComingSoon?: boolean;
};

export const SEED_PRODUCTS: SeedProduct[] = [
  // ── NEW (May 2026 spec): four featured products from the master prompt ──
  // The "Babies Complete Learning Bundle" has no commissioned image yet —
  // tonal placeholder is the honest skeleton. The other three have real
  // photos registered in src/lib/images.ts → products.
  {
    slug: "owl-babies-bundle",
    title: "OWL Babies Complete Learning Bundle",
    price: "$129",
    ageRange: "0–2",
    ageBand: "0-1",
    category: "Digital",
    tone: "amber",
    channel: "gumroad",
    story:
      "A starter bundle for a baby's first OWL year — plush companion, bilingual flash cards, movement activity pack, and Larissa's lullaby album. Built for sensory exploration, attachment routines, and slow-paced bedtime learning.",
    supportsLearningIn: [
      "Plush owl",
      "Bilingual flash cards",
      "Movement activity pack",
      "Lullaby album",
      "Sensory learning",
      "Educational bundle",
    ],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "larissa-plush",
    title: "Larissa Plush Set — 6 Ethnicities",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "amber",
    channel: "printify",
    story:
      "Six 10-inch Larissa plush companions — Black/African American, Latina, Asian, White, Middle Eastern, and Native American — each soft, huggable, and dressed in OWL's signature jacket. Removable outfits for pretend-play.",
    supportsLearningIn: [
      "Diverse representation",
      "Removable outfits",
      "Educational",
      "Safe for all ages",
    ],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "rhyme-time-game",
    title: "OWL Rhyme Time Card Game",
    price: "$12.99",
    ageRange: "4–5",
    ageBand: "4-5",
    category: "Flashcards",
    tone: "rose",
    channel: "printify",
    story:
      "48 thick rhyming cards with four ways to play (Go Fish · Rhyme Match · Memory Match · Rhyme Snap). Builds early literacy through rhyming patterns kids love.",
    supportsLearningIn: [
      "Literacy building",
      "Rhyming skills",
      "Memory games",
      "Ages 4–5",
    ],
    featured: true,
    isComingSoon: true,
  },
  // ── EXTRA: actual uploaded image was "Big Feelings Poster Set" ($18.99),
  //    not the bundle from the prompt. Adding both — bundle gets the slot,
  //    posters get the actual image so nothing is wasted.
  {
    slug: "big-feelings-posters",
    title: "OWL Big Feelings Poster Set",
    price: "$18.99",
    ageRange: "3–4",
    ageBand: "3-4",
    category: "Flashcards",
    tone: "teal",
    channel: "printify",
    story:
      "Three large 11×17 laminated SEL posters designed for PreK classrooms — How Am I Feeling, What To Do When I Feel, and Daily Mood Check-In. Multicultural face photography. Reinforces emotion vocabulary and self-regulation routines.",
    supportsLearningIn: [
      "Social-emotional learning",
      "Emotion vocabulary",
      "Daily check-in routine",
      "Classroom-ready",
    ],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "bilingual-word-cards",
    title: "OWL Toddler Word Cards",
    price: "$12.99",
    ageRange: "1–4",
    ageBand: "1-2",
    category: "Flashcards",
    tone: "amber",
    channel: "printify",
    story:
      "50 large 4×4 inch bilingual EN/ES flash cards organized into five categories (People · Food · Animals · Actions · Objects). Toddler-safe construction, easy to wipe.",
    supportsLearningIn: [
      "Bilingual learning",
      "Early vocabulary",
      "Categories",
      "Toddler safe",
    ],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "abc-flash-cards",
    title: "ABC flash cards",
    price: "$19.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Flashcards",
    tone: "teal",
    channel: "printify",
    story: "26 illustrated multicultural character cards. One letter, one face, one story.",
    supportsLearningIn: ["Letter recognition", "Letter-sound", "Vocabulary"],
    featured: true,
  isComingSoon: true,
  },
  {
    slug: "feelings-coloring",
    title: "Feelings coloring book",
    price: "$12.99",
    ageRange: "2–5",
    ageBand: "3-4",
    category: "Coloring",
    tone: "rose",
    channel: "kdp",
    story: "32 pages of feelings-named scenes children can color while talking through their day.",
    supportsLearningIn: ["Emotion vocabulary", "Fine motor", "SEL"],
    featured: true,
  isComingSoon: true,
  },
  {
    slug: "sticker-reward-chart",
    title: "Sticker reward chart",
    price: "$13.99",
    ageRange: "3–7",
    ageBand: "3-4",
    category: "Stickers",
    tone: "forest",
    channel: "printify",
    story: "OWL character stickers on a six-week chart. Build routines without shame-based rewards.",
    supportsLearningIn: ["Routine building", "Goal tracking", "Self-efficacy"],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "homeschool-starter",
    title: "Homeschool starter bundle",
    price: "$34.99",
    ageRange: "2–5",
    ageBand: "3-4",
    category: "Digital",
    tone: "cream",
    channel: "gumroad",
    story: "A digital starter pack with twelve printable activities, a parent guide, and access to four OWL videos.",
    supportsLearningIn: ["Early literacy", "Counting", "SEL", "Cultural awareness"],
  isComingSoon: true,
  },
  {
    slug: "lullaby-album",
    title: "Larissa's lullaby album",
    price: "$7.99",
    ageRange: "0–3",
    ageBand: "0-1",
    category: "Music",
    tone: "mist",
    channel: "gumroad",
    story: "Eleven original lullabies — recorded at 432 Hz for a calmer bedtime.",
    supportsLearningIn: ["Sleep routines", "Emotional regulation"],
    featured: true,
    isComingSoon: true,
  },
  {
    slug: "owl-counting-mat",
    title: "OWL counting mat 1–20",
    price: "$8.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Flashcards",
    tone: "amber",
    channel: "printify",
    story: "A laminated, wipe-clean mat with number 1–20 and one-to-one counting practice spaces.",
    supportsLearningIn: ["Counting", "Numeral recognition", "1:1 correspondence"],
  isComingSoon: true,
  },
  {
    slug: "emotion-tiles",
    title: "OWL emotion tiles",
    price: "$13.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Flashcards",
    tone: "rose",
    channel: "printify",
    story: "Twelve double-sided tiles with multicultural faces showing big feelings — perfect for circle time.",
    supportsLearningIn: ["Emotion vocabulary", "Empathy", "Storytelling"],
  isComingSoon: true,
  },
  {
    slug: "kreadiness-checklist",
    title: "K-readiness checklist",
    price: "$5.99",
    ageRange: "4–5",
    ageBand: "4-5",
    category: "Flashcards",
    tone: "teal",
    channel: "printify",
    story: "A 3-page laminated checklist tied to Common Core kindergarten standards and ELOF 60-month indicators.",
    supportsLearningIn: ["K-readiness", "Parent communication", "Standards alignment"],
  isComingSoon: true,
  },
  // ── Plush sets — May 2026 ────────────────────────────────────────────────
  {
    slug: "plush-bedtime-friends",
    title: "Larissa Plush Set — 6 Bedtime Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "mist",
    channel: "printify",
    story: "Six 10-inch bedtime owl companions — Dreamy Star, Sleepy Moon, Cloudy, Twinkle, Nighty Night, and Baby Owl. Perfect for calming bedtime routines and lullaby sing-alongs.",
    supportsLearningIn: ["Sleep routines", "Comfort objects", "Imaginative play", "Safe for all ages"],
    isComingSoon: true,
  },
  {
    slug: "plush-forest-friends",
    title: "Larissa Plush Set — 6 Forest Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "forest",
    channel: "printify",
    story: "Six nature-inspired owl plush companions — Fox, Bear, Deer, Raccoon, Hedgehog, and Forest Owl — each dressed in OWL's signature jacket. Inspired by the natural world.",
    supportsLearningIn: ["Nature vocabulary", "Animal recognition", "Imaginative play", "Educational"],
    isComingSoon: true,
  },
  {
    slug: "plush-ocean-friends",
    title: "Larissa Plush Set — 6 Ocean Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "teal",
    channel: "printify",
    story: "Six ocean-themed owl companions — Dolphin, Sea Turtle, Clownfish, Whale, Starfish, and Octopus. Bright colors and ocean-inspired fun for little explorers.",
    supportsLearningIn: ["Ocean vocabulary", "Marine life", "Imaginative play", "Educational"],
    isComingSoon: true,
  },
  {
    slug: "plush-safari-friends",
    title: "Larissa Plush Set — 6 Safari Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "amber",
    channel: "printify",
    story: "Six safari animal owl companions — Elephant, Giraffe, Lion, Zebra, Monkey, and Tiger. Wild about animals and educational fun.",
    supportsLearningIn: ["Animal vocabulary", "Safari animals", "Imaginative play", "Educational"],
    isComingSoon: true,
  },
  {
    slug: "plush-space-friends",
    title: "Larissa Plush Set — 6 Space Friends",
    price: "$34.99",
    ageRange: "0–5",
    ageBand: "0-1",
    category: "Plush",
    tone: "rose",
    channel: "printify",
    story: "Six out-of-this-world owl companions — Astronaut Owl, Alien Friend, Rocket Pilot, Planet Explorer, Comet Buddy, and Galaxy Girl. For little dreamers who reach for the stars.",
    supportsLearningIn: ["Space vocabulary", "STEM curiosity", "Imaginative play", "Educational"],
    isComingSoon: true,
  },
  // ── Music albums — May 2026 ──────────────────────────────────────────────
  {
    slug: "counting-math-album",
    title: "Larissa's Counting & Math Party!",
    price: "$9.99",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Music",
    tone: "amber",
    channel: "gumroad",
    story: "Fun songs about numbers, shapes, patterns, and more — recorded at a toddler-friendly tempo with call-and-response phrasing.",
    supportsLearningIn: ["Counting", "Number recognition", "Shapes", "Patterns"],
    isComingSoon: true,
  },
  {
    slug: "abc-adventure-album",
    title: "Larissa's ABC Adventure Songs",
    price: "$9.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Music",
    tone: "teal",
    channel: "gumroad",
    story: "Catchy songs to learn letters, phonics, and spelling — each track focuses on a letter cluster with memorable melodies.",
    supportsLearningIn: ["Letter recognition", "Phonics", "Spelling", "Early literacy"],
    isComingSoon: true,
  },
  {
    slug: "around-world-album",
    title: "Larissa's Around the World",
    price: "$9.99",
    ageRange: "2–8",
    ageBand: "2-3",
    category: "Music",
    tone: "rose",
    channel: "gumroad",
    story: "Songs about cultures we love — explore, learn, and sing together. Multicultural musical celebration for the whole family.",
    supportsLearningIn: ["Cultural awareness", "World music", "Multicultural vocabulary", "Global citizenship"],
    isComingSoon: true,
  },
  {
    slug: "calm-down-album",
    title: "Larissa's Calm Down & Mindfulness Songs",
    price: "$9.99",
    ageRange: "2–8",
    ageBand: "2-3",
    category: "Music",
    tone: "mist",
    channel: "gumroad",
    story: "Gentle songs to help little hearts and minds feel calm and happy. Breathe. Relax. Be Kind.",
    supportsLearningIn: ["Mindfulness", "Emotional regulation", "Breathing exercises", "SEL"],
    isComingSoon: true,
  },
  // ── Coloring books — May 2026 ────────────────────────────────────────────
  {
    slug: "numbers-math-coloring",
    title: "OWL Numbers & Math Magic Coloring Book",
    price: "$7.99",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Coloring",
    tone: "amber",
    channel: "kdp",
    story: "Count and color your way through numbers 1–20 with OWL. Each page pairs a numeral with matching objects to count and color.",
    supportsLearningIn: ["Counting", "Number recognition", "Fine motor", "Math concepts"],
    isComingSoon: true,
  },
  {
    slug: "abc-coloring-book",
    title: "OWL ABC Coloring Book",
    price: "$7.99",
    ageRange: "2–5",
    ageBand: "2-3",
    category: "Coloring",
    tone: "teal",
    channel: "kdp",
    story: "A is for Owl — 26 letter pages with OWL characters to color while learning the alphabet.",
    supportsLearningIn: ["Letter recognition", "Fine motor", "Early literacy", "Creative expression"],
    isComingSoon: true,
  },
  {
    slug: "abcs-world-coloring",
    title: "OWL ABCs Around the World Coloring Book",
    price: "$8.99",
    ageRange: "2–6",
    ageBand: "2-3",
    category: "Coloring",
    tone: "rose",
    channel: "kdp",
    story: "A Multicultural Alphabet Coloring Book — each letter features a child from a different culture with their traditional dress and a meaningful word.",
    supportsLearningIn: ["Letter recognition", "Multicultural awareness", "Fine motor", "Global vocabulary"],
    isComingSoon: true,
  },
  // ── Sticker sets — May 2026 ──────────────────────────────────────────────
  {
    slug: "owl-emotions-stickers",
    title: "OWL Emotions Sticker Set",
    price: "$5.99",
    ageRange: "2–7",
    ageBand: "2-3",
    category: "Stickers",
    tone: "rose",
    channel: "printify",
    story: "12 owl emotion face stickers — Happy, Sad, Angry, Calm, Excited, Worried, Scared, Sleepy, Surprised, Silly, Loved, and Proud. Perfect for feelings check-ins.",
    supportsLearningIn: ["Emotion vocabulary", "SEL", "Feelings identification", "Self-awareness"],
    isComingSoon: true,
  },
  {
    slug: "owl-cultural-stickers",
    title: "OWL Cultural Celebrations Sticker Bundle",
    price: "$6.99",
    ageRange: "3–8",
    ageBand: "3-4",
    category: "Stickers",
    tone: "amber",
    channel: "printify",
    story: "12 multicultural holiday owl stickers — Diwali, Kwanzaa, Hanukkah, Lunar New Year, Eid, Holi, Juneteenth, Día de Muertos, Carnival, Nowruz, Christmas, and Thanksgiving.",
    supportsLearningIn: ["Cultural awareness", "Holiday vocabulary", "Multicultural education", "Global citizenship"],
    isComingSoon: true,
  },
  {
    slug: "owl-baby-girl-stickers",
    title: "Baby Girl OWL Sticker Sheet",
    price: "$4.99",
    ageRange: "0–2",
    ageBand: "0-1",
    category: "Stickers",
    tone: "rose",
    channel: "printify",
    story: "12 pastel baby owl stickers — Bow, Heart, Daisy, Cozy, Rattle, Binky, Bottle, Dream, Star, Flutter, Princess, and Sweet Hoot. A sweet gift for little ones.",
    supportsLearningIn: ["Reward system", "Fine motor", "Imaginative play", "Gift giving"],
    isComingSoon: true,
  },
  {
    slug: "owl-big-kid-boy-stickers",
    title: "Big Kid Boy OWL Sticker Sheet",
    price: "$4.99",
    ageRange: "3–5",
    ageBand: "3-4",
    category: "Stickers",
    tone: "teal",
    channel: "printify",
    story: "12 adventure owl stickers for big kids — School, Soccer, Read, Write, Star, Strong, Dream Big, Cool, Create, High Five, Champ, and I Am Brave.",
    supportsLearningIn: ["Growth mindset", "Reward system", "Self-confidence", "Achievement recognition"],
    isComingSoon: true,
  },
];

export const PRODUCT_CATEGORY_OPTIONS = [
  { value: "Plush", label: "Plush" },
  { value: "Flashcards", label: "Flashcards" },
  { value: "Coloring", label: "Coloring" },
  { value: "Stickers", label: "Stickers" },
  { value: "Digital", label: "Digital" },
  { value: "Music", label: "Music" },
] as const;

export function findProductBySlug(slug: string) {
  return SEED_PRODUCTS.find((p) => p.slug === slug);
}
