import { NextResponse } from "next/server";
import { SEED_PRODUCTS } from "@/lib/seed/products";
import { PAYPAL_BASE } from "@/lib/paypal-server";

/**
 * POST /api/webhooks/paypal
 *
 * Handles PayPal webhook events for the OWL store.
 * When payment completes → auto-creates a Printful order for fulfillment.
 *
 * ── SETUP (do once in PayPal Developer Dashboard) ────────────────────────
 * 1. developer.paypal.com → My Apps → Your App → Webhooks → Add Webhook
 * 2. URL: https://www.owlsingtogether.com/api/webhooks/paypal
 * 3. Events:
 *      CHECKOUT.ORDER.APPROVED
 *      PAYMENT.CAPTURE.COMPLETED
 *      PAYMENT.CAPTURE.DENIED
 *      PAYMENT.CAPTURE.REFUNDED
 * 4. Copy the Webhook ID → Vercel → Settings → Environment Variables → PAYPAL_WEBHOOK_ID
 *
 * ── ENV VARS REQUIRED ────────────────────────────────────────────────────
 *   PAYPAL_WEBHOOK_ID              — from PayPal Developer Dashboard → Webhooks
 *   NEXT_PUBLIC_PAYPAL_CLIENT_ID   — PayPal app client ID
 *   PAYPAL_CLIENT_SECRET           — PayPal app secret
 *   PRINTFUL_API_KEY               — Printful Dashboard → Settings → API
 *   NEXT_PUBLIC_SUPABASE_URL + NEXT_PUBLIC_SUPABASE_ANON_KEY  (optional, for order storage)
 *
 * ── PRINTFUL STORE ───────────────────────────────────────────────────────
 *   Store ID 18286248 (OwlSingTogetherStore — Etsy) is hardcoded below.
 *   Run scripts/fetch-printful-variant-ids.js to generate src/lib/printful-variants.ts
 *   whenever you add new products.
 */

// Import variant map generated by scripts/fetch-printful-variant-ids.js
// Falls back gracefully to manual review if file doesn't exist yet.
let getPrintfulVariantId: (slug: string) => number | null = () => null;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const variantModule = require("@/lib/printful-variants");
  getPrintfulVariantId = variantModule.getPrintfulVariantId ?? (() => null);
} catch {
  // printful-variants.ts not generated yet — all orders go to manual review
}

const PRINTFUL_STORE_ID = 18286248; // OwlSingTogetherStore (Etsy-connected)

// ── In-memory idempotency guard ──────────────────────────────────────────────
const processedEvents = new Set<string>();

// ── Types ────────────────────────────────────────────────────────────────────
interface PayPalWebhookEvent {
  id: string;
  event_type: string;
  resource_type: string;
  resource: {
    id: string;
    status?: string;
    supplementary_data?: { related_ids?: { order_id?: string } };
    purchase_units?: Array<{
      description?: string;
      custom_id?: string;
      amount: { value: string; currency_code: string };
      shipping?: {
        name?: { full_name?: string };
        address?: {
          address_line_1?: string;
          address_line_2?: string;
          admin_area_2?: string;
          admin_area_1?: string;
          postal_code?: string;
          country_code?: string;
        };
      };
      items?: Array<{
        name: string;
        unit_amount: { value: string };
        quantity: string;
        sku?: string;
      }>;
    }>;
    payer?: {
      email_address?: string;
      name?: { given_name?: string; surname?: string };
    };
  };
}

interface LineItem {
  name: string;
  sku: string;
  quantity: number;
  unit_price: string;
  printful_variant_id: number | null;
  fulfillment_ready: boolean;
}

interface OrderRecord {
  paypal_event_id: string;
  paypal_order_id: string;
  status: string;
  customer_email: string;
  shipping_name: string;
  shipping_address: Record<string, string>;
  line_items: LineItem[];
  printful_order_id?: string;
  manual_review_reason?: string;
  total_amount: string;
  currency: string;
  raw_event: unknown;
  created_at: string;
}

// ── PayPal signature verification ────────────────────────────────────────────
async function verifyPayPalSignature(req: Request, rawBody: string): Promise<boolean> {
  const webhookId = process.env.PAYPAL_WEBHOOK_ID;
  if (!webhookId) {
    console.warn("[PayPal Webhook] PAYPAL_WEBHOOK_ID not set — skipping verification");
    return true;
  }

  const transmissionId   = req.headers.get("paypal-transmission-id") ?? "";
  const transmissionTime = req.headers.get("paypal-transmission-time") ?? "";
  const certUrl          = req.headers.get("paypal-cert-url") ?? "";
  const transmissionSig  = req.headers.get("paypal-transmission-sig") ?? "";
  const authAlgo         = req.headers.get("paypal-auth-algo") ?? "";

  if (!transmissionId || !transmissionTime || !certUrl || !transmissionSig) {
    console.error("[PayPal Webhook] Missing signature headers");
    return false;
  }

  try {
    const clientId     = process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID ?? "";
    const clientSecret = process.env.PAYPAL_CLIENT_SECRET ?? "";

    const tokenRes = await fetch(`${PAYPAL_BASE}/v1/oauth2/token`, {
      method: "POST",
      headers: {
        Authorization: `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: "grant_type=client_credentials",
    });

    if (!tokenRes.ok) {
      console.warn("[PayPal Webhook] Token fetch failed — allowing through");
      return true;
    }

    const { access_token } = await tokenRes.json() as { access_token: string };

    const verifyRes = await fetch(`${PAYPAL_BASE}/v1/notifications/verify-webhook-signature`, {
      method: "POST",
      headers: { Authorization: `Bearer ${access_token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        auth_algo: authAlgo,
        cert_url: certUrl,
        transmission_id: transmissionId,
        transmission_sig: transmissionSig,
        transmission_time: transmissionTime,
        webhook_id: webhookId,
        webhook_event: JSON.parse(rawBody),
      }),
    });

    if (!verifyRes.ok) return false;
    const { verification_status } = await verifyRes.json() as { verification_status: string };
    return verification_status === "SUCCESS";
  } catch (err) {
    console.error("[PayPal Webhook] Verification error:", err);
    return true; // fail open on transient network error
  }
}

// ── Save order to Supabase (optional) ────────────────────────────────────────
async function saveOrderToSupabase(order: OrderRecord): Promise<void> {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!supabaseUrl || !supabaseKey) return;

  try {
    const res = await fetch(`${supabaseUrl}/rest/v1/orders`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: supabaseKey,
        Authorization: `Bearer ${supabaseKey}`,
        Prefer: "return=minimal",
      },
      body: JSON.stringify({
        external_id:    order.paypal_order_id,
        source:         "paypal",
        customer_email: order.customer_email,
        total_cents:    Math.round(parseFloat(order.total_amount) * 100),
        currency:       order.currency,
        status:         order.printful_order_id ? "fulfilled" : order.status,
        line_items:     order.line_items,
        placed_at:      order.created_at,
        raw_payload:    order.raw_event,
      }),
    });
    if (!res.ok) console.error("[PayPal Webhook] Supabase save failed:", await res.text());
    else console.log("[PayPal Webhook] Order saved to Supabase:", order.paypal_order_id);
  } catch (err) {
    console.error("[PayPal Webhook] Supabase error:", err);
  }
}

// ── Find product in seed by SKU or name ──────────────────────────────────────
function findProductBySku(sku: string, name: string) {
  if (sku) {
    const bySlug = SEED_PRODUCTS.find(p => p.slug === sku);
    if (bySlug) return bySlug;
  }
  const nameLower = name.toLowerCase();
  return SEED_PRODUCTS.find(p => p.title.toLowerCase().includes(nameLower.slice(0, 12)));
}

// ── Create Printful order ─────────────────────────────────────────────────────
async function createPrintfulOrder(
  orderId: string,
  customerEmail: string,
  shippingName: string,
  addr: Record<string, string>,
  items: LineItem[],
): Promise<{ ok: boolean; printfulOrderId?: string; error?: string }> {
  const apiKey = process.env.PRINTFUL_API_KEY;
  if (!apiKey) return { ok: false, error: "PRINTFUL_API_KEY not configured in Vercel" };

  const firstName = shippingName.split(" ")[0] ?? "Customer";
  const lastName  = shippingName.split(" ").slice(1).join(" ") || ".";

  const payload = {
    external_id: `OWL-${orderId.slice(-8).toUpperCase()}`,
    shipping:    "STANDARD",
    recipient: {
      name:         shippingName || "Customer",
      first_name:   firstName,
      last_name:    lastName,
      email:        customerEmail,
      phone:        "",
      address1:     addr.address1,
      address2:     addr.address2 ?? "",
      city:         addr.city,
      state_code:   addr.state,
      country_code: addr.country || "US",
      zip:          addr.zip,
    },
    items: items
      .filter(i => i.printful_variant_id !== null)
      .map(i => ({
        sync_variant_id: i.printful_variant_id,
        quantity:        i.quantity,
        retail_price:    i.unit_price,
        name:            i.name,
      })),
  };

  if (!payload.items.length) {
    return { ok: false, error: "No items with Printful variant IDs — run fetch-printful-variant-ids.js" };
  }

  const res = await fetch("https://api.printful.com/orders", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "X-PF-Store-Id": String(PRINTFUL_STORE_ID),
      "Content-Type":  "application/json",
    },
    body: JSON.stringify(payload),
  });

  const data = await res.json() as { result?: { id: number }; code?: number; error?: unknown };

  if (!res.ok) {
    const errMsg = JSON.stringify(data.error ?? data).slice(0, 300);
    return { ok: false, error: `Printful API ${res.status}: ${errMsg}` };
  }

  return { ok: true, printfulOrderId: String(data.result?.id ?? "") };
}

// ── Main webhook handler ──────────────────────────────────────────────────────
export async function POST(req: Request) {
  const rawBody = await req.text();
  let event: PayPalWebhookEvent;

  try {
    event = JSON.parse(rawBody);
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const eventId = event.id ?? "";
  console.log("[PayPal Webhook] Received:", event.event_type, "| ID:", eventId);

  // Idempotency
  if (processedEvents.has(eventId)) {
    return NextResponse.json({ received: true, action: "duplicate_ignored" });
  }

  // Signature verification
  const signatureValid = await verifyPayPalSignature(
    new Request(req.url, { method: req.method, headers: req.headers, body: rawBody }),
    rawBody,
  );
  if (!signatureValid) {
    return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
  }

  processedEvents.add(eventId);
  if (processedEvents.size > 500) {
    const first = processedEvents.values().next().value;
    if (first) processedEvents.delete(first);
  }

  // ── Non-fulfillment events ──
  if (event.event_type === "PAYMENT.CAPTURE.DENIED") {
    return NextResponse.json({ received: true, action: "payment_denied" });
  }
  if (event.event_type === "PAYMENT.CAPTURE.REFUNDED") {
    console.warn("[PayPal Webhook] Refund — cancel Printful order manually if not yet shipped");
    return NextResponse.json({ received: true, action: "refunded" });
  }
  if (event.event_type === "CHECKOUT.ORDER.APPROVED") {
    return NextResponse.json({ received: true, action: "order_approved_awaiting_capture" });
  }
  if (event.event_type !== "PAYMENT.CAPTURE.COMPLETED") {
    return NextResponse.json({ received: true, action: "ignored" });
  }

  // ── PAYMENT.CAPTURE.COMPLETED — fulfillment trigger ──
  const unit     = event.resource?.purchase_units?.[0];
  const payer    = event.resource?.payer;
  const shipping = unit?.shipping;
  const addr     = shipping?.address;

  const customerEmail = payer?.email_address ?? "";
  const shippingName  = shipping?.name?.full_name
    ?? `${payer?.name?.given_name ?? ""} ${payer?.name?.surname ?? ""}`.trim();
  const orderId       = event.resource.supplementary_data?.related_ids?.order_id ?? event.resource.id;
  const totalAmount   = unit?.amount?.value ?? "0";
  const currency      = unit?.amount?.currency_code ?? "USD";

  const addrMap = {
    address1: addr?.address_line_1 ?? "",
    address2: addr?.address_line_2 ?? "",
    city:     addr?.admin_area_2 ?? "",
    state:    addr?.admin_area_1 ?? "",
    zip:      addr?.postal_code ?? "",
    country:  addr?.country_code ?? "US",
  };

  // Build line items — map slug to Printful sync_variant_id
  const lineItems: LineItem[] = (unit?.items ?? []).map(item => {
    const product = findProductBySku(item.sku ?? "", item.name);
    const slug    = item.sku ?? product?.slug ?? "";
    const varId   = getPrintfulVariantId(slug);

    return {
      name:                item.name,
      sku:                 slug,
      quantity:            parseInt(item.quantity, 10),
      unit_price:          item.unit_amount?.value ?? "0",
      printful_variant_id: varId,
      fulfillment_ready:   varId !== null,
    };
  });

  const allReady     = lineItems.length > 0 && lineItems.every(i => i.fulfillment_ready);
  const missingItems = lineItems.filter(i => !i.fulfillment_ready);

  const orderRecord: OrderRecord = {
    paypal_event_id:  eventId,
    paypal_order_id:  orderId,
    status:           "paid",
    customer_email:   customerEmail,
    shipping_name:    shippingName,
    shipping_address: addrMap,
    line_items:       lineItems,
    total_amount:     totalAmount,
    currency,
    raw_event:        event,
    created_at:       new Date().toISOString(),
  };

  // Manual review path
  if (!allReady) {
    const reasons: string[] = [];
    if (!process.env.PRINTFUL_API_KEY) reasons.push("PRINTFUL_API_KEY not in Vercel env vars");
    if (missingItems.length > 0) {
      reasons.push(`Missing Printful variant ID for: ${missingItems.map(i => i.name).join(", ")}`);
      reasons.push("Fix: node scripts/fetch-printful-variant-ids.js → commit → push");
    }

    orderRecord.status = "manual_review_required";
    orderRecord.manual_review_reason = reasons.join("; ");

    console.warn("[PayPal Webhook] ⚠️  MANUAL REVIEW REQUIRED:", JSON.stringify({
      orderId, customer: customerEmail, reasons,
      items: lineItems.map(i => ({ name: i.name, qty: i.quantity, ready: i.fulfillment_ready })),
      shippingTo: addrMap,
    }, null, 2));

    await saveOrderToSupabase(orderRecord);

    return NextResponse.json({
      received: true,
      action:   "manual_review_required",
      orderId,
      customer: customerEmail,
      reasons,
      items:    lineItems.map(i => ({ name: i.name, qty: i.quantity, ready: i.fulfillment_ready })),
    });
  }

  // Auto-fulfillment via Printful
  const result = await createPrintfulOrder(orderId, customerEmail, shippingName, addrMap, lineItems);

  if (!result.ok) {
    console.error("[PayPal Webhook] Printful order FAILED:", result.error);
    orderRecord.status = "fulfillment_failed";
    orderRecord.manual_review_reason = result.error;
    await saveOrderToSupabase(orderRecord);
    return NextResponse.json({ error: "Printful order failed", details: result.error }, { status: 500 });
  }

  console.log("[PayPal Webhook] ✅ Printful order created:", result.printfulOrderId);
  orderRecord.status = "submitted_to_printful";
  orderRecord.printful_order_id = result.printfulOrderId;
  await saveOrderToSupabase(orderRecord);

  return NextResponse.json({
    received:        true,
    action:          "auto_fulfilled",
    orderId,
    printfulOrderId: result.printfulOrderId,
    customer:        customerEmail,
    items:           lineItems.map(i => ({ name: i.name, qty: i.quantity })),
  });
}

// ── GET — credential + readiness check ───────────────────────────────────────
export async function GET() {
  let variantsLoaded = false;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require("@/lib/printful-variants");
    variantsLoaded = true;
  } catch { /* not generated yet */ }

  return NextResponse.json({
    status:         "PayPal → Printful webhook active",
    webhook_url:    "https://www.owlsingtogether.com/api/webhooks/paypal",
    fulfillment:    "Printful",
    printful_store: `Store ID ${PRINTFUL_STORE_ID} (OwlSingTogetherStore / Etsy)`,
    credentials: {
      PAYPAL_WEBHOOK_ID:            process.env.PAYPAL_WEBHOOK_ID            ? "✅ set" : "❌ missing",
      NEXT_PUBLIC_PAYPAL_CLIENT_ID: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID ? "✅ set" : "❌ missing",
      PAYPAL_CLIENT_SECRET:         process.env.PAYPAL_CLIENT_SECRET         ? "✅ set" : "❌ missing",
      PRINTFUL_API_KEY:             process.env.PRINTFUL_API_KEY             ? "✅ set" : "❌ missing",
      SUPABASE:                     (process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL) ? "✅ set" : "⚠️  optional",
    },
    variant_map:            variantsLoaded ? "✅ loaded" : "❌ run fetch-printful-variant-ids.js",
    auto_fulfillment_ready: variantsLoaded && !!process.env.PRINTFUL_API_KEY,
  });
}
